from setuptools import setup, find_packages

setup(
  name = 'robocat',
  packages = find_packages(exclude=[]),
  version = '0.0.4',
  license='MIT',
  description = 'Robo CAT- Pytorch',
  author = 'Kye Gomez',
  author_email = 'kye@apac.ai',
  long_description_content_type = 'text/markdown',
  url = 'https://github.com/kyegomez/RoboCAT',
  keywords = [
    'artificial intelligence',
    'deep learning',
    'transformers',
    'attention mechanism',
    'robotics'
  ],
  install_requires=[
      'transformers',
      'torch',
      'einops',
      'beartype',
      'palme',
      'transformers',
      'palm-rlhf-pytorch',
      'tokenizers',
      'wandb',
      'classifier-free-guidance-pytorch',
      'axial_positional_embedding',
      'DALL-E',
      'einops>=0.3.2',
      'ftfy',
      'packaging',
      'pillow',
      'regex',
      'rotary-embedding-torch',
      'taming-transformers-rom1504',
      'tokenizers',
      'torch>=1.6',
      'torchvision',
      'transformers',
      'tqdm',
      'youtokentome',
      'WebDataset'
  ],
  classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.6',
  ],
)